INSERT INTO tbt_user_api(ID,USERNAME, PASSWORD) VALUES(1,'Phuhq','0685');
INSERT INTO tbt_user_api(ID,USERNAME, PASSWORD) VALUES(2,'Nganm','0037');
INSERT INTO tbt_user_api(ID,USERNAME, PASSWORD) VALUES(3,'Longnd','0095');
INSERT INTO tbt_user_api(ID,USERNAME, PASSWORD) VALUES(4,'Quytt','0086');

COMMIT;